// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/PermissionData/log (interfaces: Logger)

package mock_log

import (
	log "github.com/PermissionData/log"
	gomock "github.com/golang/mock/gomock"
)

// Mock of Logger interface
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *_MockLoggerRecorder
}

// Recorder for MockLogger (not exported)
type _MockLoggerRecorder struct {
	mock *MockLogger
}

func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &_MockLoggerRecorder{mock}
	return mock
}

func (_m *MockLogger) EXPECT() *_MockLoggerRecorder {
	return _m.recorder
}

func (_m *MockLogger) Log(_param0 log.Level, _param1 log.Data) {
	_m.ctrl.Call(_m, "Log", _param0, _param1)
}

func (_mr *_MockLoggerRecorder) Log(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Log", arg0, arg1)
}
